INSERT INTO post (title, subtitle, author, author_url, publish_date, image_url, featured)
VALUES 
  ('photography', 'The Road Ahead', 'The road ahead might be paved - it might not be.', 'Mat Vogels', 
  '../static/sources/Mat-Vogles.svg', 'September 25, 201', 
  '../static/sources/the-road-ahead-background.jpg', 1), 
  ('adventure', 'From Top Down', "Once a year, go someplace you've never been before.", 'William Wong', 
  '../static/sources/William-Wong.svg', 'September 25, 201', 
  '../static/sources/from-top-down-background.jpg', 1),
  ('nature', 'Still Standing Tall', 'Life begins at the end of your comfort zone.', 'William Wong', 
  '../static/sources/William-Wong.svg', '9/25/2015', 
  '../static/sources/still-standing-tall-background.jpg', 0),
  ('photography', 'Sunny Side Up', "No place is ever as bad as they tell you it's going to be.", 'Mat Vogels', 
  '../static/sources/Mat-Vogles.svg', '9/25/2015', 
  '../static/sources/sunny-side-up-background.jpg', 0),
  ('relaxation', 'Water Falls', "We travel not to escape life, but for life not to escape us.", 'Mat Vogels', 
  '../static/sources/Mat-Vogles.svg', '9/25/2015', 
  '../static/sources/water-falls-background.jpg', 0),
  ('vacation', 'Through the Mist', "Travel makes you see what a tiny place you occupy in the world.", 'William Wong', 
  '../static/sources/William-Wong.svg', '9/25/2015', 
  '../static/sources/trough-the-mist-background.jpg', 0),
  ('vacation', 'Awaken Early', "Not all those who wander are lost.", 'Mat Vogels', 
  '../static/sources/Mat-Vogles.svg', '9/25/2015', 
  '../static/sources/awaken-early-background.jpg', 0),
  ('travel', 'Try it Always', "The world is a book, and those who do not travel read only one page.", 'Mat Vogels', 
  '../static/sources/Mat-Vogles.svg', '9/25/2015', 
  '../static/sources/try-it-always-background.jpg', 0);